# -*- coding: utf-8 -*-
"""Processamento de Imagem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncDy8eyNzAVfirc-dNgX7iWnFIzsaXrL
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

image_paths = ['clara.jpg', 'imagem.jpg', 'escura.jpg', 'imagens.jpg']
images = []

for path in image_paths:
  img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
  images.append(img)

for image in images:
  # Equalização do histograma
  imagem_equalizada = cv2.equalizeHist(image)

  # Negativo da imagem
  imagem_negativa = 255 - image

  # Segmentação por intervalo de intensidade
  intervalo_min = 100
  intervalo_max = 200
  mascara = cv2.inRange(image, intervalo_min, intervalo_max)

  # Mostrar as imagens
  cv2_imshow(image)
  cv2_imshow(imagem_equalizada)
  cv2_imshow(imagem_negativa)
  cv2_imshow(mascara)
  cv2.waitKey(0)
  cv2.destroyAllWindows()